type LocalizationType = {
  _id: string;
  name: string;
  region: string;
};

export const LOCALIZATIONS: LocalizationType[] = [
  // Worldwide: [
  { _id: "WW", name: "Worldwide", region: "Worldwide" },
  // ],
  // Americas: [
  { _id: "AI", name: "Anguilla", region: "Americas" },
  { _id: "AG", name: "Antigua and Barbuda", region: "Americas" },
  { _id: "AR", name: "Argentina", region: "Americas" },
  { _id: "AW", name: "Aruba", region: "Americas" },
  { _id: "BS", name: "Bahamas", region: "Americas" },
  { _id: "BB", name: "Barbados", region: "Americas" },
  { _id: "BZ", name: "Belize", region: "Americas" },
  { _id: "BM", name: "Bermuda", region: "Americas" },
  { _id: "BO", name: "Bolivia", region: "Americas" },
  { _id: "BR", name: "Brazil", region: "Americas" },
  { _id: "VG", name: "British Virgin Islands", region: "Americas" },
  { _id: "CA", name: "Canada", region: "Americas" },
  { _id: "BQ", name: "Caribbean Netherlands", region: "Americas" },
  { _id: "KY", name: "Cayman Islands", region: "Americas" },
  { _id: "CL", name: "Chile", region: "Americas" },
  { _id: "CO", name: "Colombia", region: "Americas" },
  { _id: "CR", name: "Costa Rica", region: "Americas" },
  { _id: "CU", name: "Cuba", region: "Americas" },
  { _id: "CW", name: "Curaçao", region: "Americas" },
  { _id: "DM", name: "Dominica", region: "Americas" },
  { _id: "DO", name: "Dominican Republic", region: "Americas" },
  { _id: "EC", name: "Ecuador", region: "Americas" },
  { _id: "SV", name: "El Salvador", region: "Americas" },
  { _id: "FK", name: "Falkland Islands", region: "Americas" },
  { _id: "GF", name: "French Guiana", region: "Americas" },
  { _id: "GL", name: "Greenland", region: "Americas" },
  { _id: "GD", name: "Grenada", region: "Americas" },
  { _id: "GP", name: "Guadeloupe", region: "Americas" },
  { _id: "GT", name: "Guatemala", region: "Americas" },
  { _id: "GY", name: "Guyana", region: "Americas" },
  { _id: "HT", name: "Haiti", region: "Americas" },
  { _id: "HN", name: "Honduras", region: "Americas" },
  { _id: "JM", name: "Jamaica", region: "Americas" },
  { _id: "MQ", name: "Martinique", region: "Americas" },
  { _id: "MX", name: "Mexico", region: "Americas" },
  { _id: "MS", name: "Montserrat", region: "Americas" },
  { _id: "NI", name: "Nicaragua", region: "Americas" },
  { _id: "PA", name: "Panama", region: "Americas" },
  { _id: "PY", name: "Paraguay", region: "Americas" },
  { _id: "PE", name: "Peru", region: "Americas" },
  { _id: "PR", name: "Puerto Rico", region: "Americas" },
  { _id: "BL", name: "Saint Barthélemy", region: "Americas" },
  { _id: "KN", name: "Saint Kitts and Nevis", region: "Americas" },
  { _id: "LC", name: "Saint Lucia", region: "Americas" },
  { _id: "MF", name: "Saint Martin", region: "Americas" },
  { _id: "PM", name: "Saint Pierre and Miquelon", region: "Americas" },
  { _id: "VC", name: "Saint Vincent and the Grenadines", region: "Americas" },
  { _id: "SX", name: "Sint Maarten", region: "Americas" },
  { _id: "SR", name: "Suriname", region: "Americas" },
  { _id: "TT", name: "Trinidad and Tobago", region: "Americas" },
  { _id: "TC", name: "Turks and Caicos Islands", region: "Americas" },
  { _id: "US", name: "United States", region: "Americas" },
  {
    _id: "UM",
    name: "United States Minor Outlying Islands",
    region: "Americas",
  },
  { _id: "VI", name: "United States Virgin Islands", region: "Americas" },
  { _id: "UY", name: "Uruguay", region: "Americas" },
  { _id: "VE", name: "Venezuela", region: "Americas" },
  // ],
  // Asia: [
  { _id: "AF", name: "Afghanistan", region: "Asia" },
  { _id: "AM", name: "Armenia", region: "Asia" },
  { _id: "AZ", name: "Azerbaijan", region: "Asia" },
  { _id: "BH", name: "Bahrain", region: "Asia" },
  { _id: "BD", name: "Bangladesh", region: "Asia" },
  { _id: "BT", name: "Bhutan", region: "Asia" },
  { _id: "BN", name: "Brunei", region: "Asia" },
  { _id: "KH", name: "Cambodia", region: "Asia" },
  { _id: "CN", name: "China", region: "Asia" },
  { _id: "GE", name: "Georgia", region: "Asia" },
  { _id: "HK", name: "Hong Kong", region: "Asia" },
  { _id: "IN", name: "India", region: "Asia" },
  { _id: "ID", name: "Indonesia", region: "Asia" },
  { _id: "IQ", name: "Iraq", region: "Asia" },
  { _id: "IL", name: "Israel", region: "Asia" },
  { _id: "JP", name: "Japan", region: "Asia" },
  { _id: "JO", name: "Jordan", region: "Asia" },
  { _id: "KZ", name: "Kazakhstan", region: "Asia" },
  { _id: "KW", name: "Kuwait", region: "Asia" },
  { _id: "KG", name: "Kyrgyzstan", region: "Asia" },
  { _id: "LA", name: "Laos", region: "Asia" },
  { _id: "LB", name: "Lebanon", region: "Asia" },
  { _id: "MO", name: "Macau", region: "Asia" },
  { _id: "MY", name: "Malaysia", region: "Asia" },
  { _id: "MV", name: "Maldives", region: "Asia" },
  { _id: "MN", name: "Mongolia", region: "Asia" },
  { _id: "MM", name: "Myanmar", region: "Asia" },
  { _id: "NP", name: "Nepal", region: "Asia" },
  { _id: "KP", name: "North Korea", region: "Asia" },
  { _id: "OM", name: "Oman", region: "Asia" },
  { _id: "PK", name: "Pakistan", region: "Asia" },
  { _id: "PS", name: "Palestine", region: "Asia" },
  { _id: "PH", name: "Philippines", region: "Asia" },
  { _id: "QA", name: "Qatar", region: "Asia" },
  { _id: "SA", name: "Saudi Arabia", region: "Asia" },
  { _id: "SG", name: "Singapore", region: "Asia" },
  { _id: "KR", name: "South Korea", region: "Asia" },
  { _id: "LK", name: "Sri Lanka", region: "Asia" },
  { _id: "SY", name: "Syria", region: "Asia" },
  { _id: "TW", name: "Taiwan", region: "Asia" },
  { _id: "TJ", name: "Tajikistan", region: "Asia" },
  { _id: "TH", name: "Thailand", region: "Asia" },
  { _id: "TL", name: "Timor-Leste", region: "Asia" },
  { _id: "TR", name: "Turkey", region: "Asia" },
  { _id: "TM", name: "Turkmenistan", region: "Asia" },
  { _id: "AE", name: "United Arab Emirates", region: "Asia" },
  { _id: "UZ", name: "Uzbekistan", region: "Asia" },
  { _id: "VN", name: "Vietnam", region: "Asia" },
  { _id: "YE", name: "Yemen", region: "Asia" },
  // ],
  // Europe: [
  { _id: "AX", name: "Åland Islands", region: "Europe" },
  { _id: "AL", name: "Albania", region: "Europe" },
  { _id: "AD", name: "Andorra", region: "Europe" },
  { _id: "AT", name: "Austria", region: "Europe" },
  { _id: "BY", name: "Belarus", region: "Europe" },
  { _id: "BE", name: "Belgium", region: "Europe" },
  { _id: "BA", name: "Bosnia and Herzegovina", region: "Europe" },
  { _id: "BG", name: "Bulgaria", region: "Europe" },
  { _id: "HR", name: "Croatia", region: "Europe" },
  { _id: "CY", name: "Cyprus", region: "Europe" },
  { _id: "CZ", name: "Czechia", region: "Europe" },
  { _id: "DK", name: "Denmark", region: "Europe" },
  { _id: "EE", name: "Estonia", region: "Europe" },
  { _id: "FO", name: "Faroe Islands", region: "Europe" },
  { _id: "FI", name: "Finland", region: "Europe" },
  { _id: "FR", name: "France", region: "Europe" },
  { _id: "DE", name: "Germany", region: "Europe" },
  { _id: "GI", name: "Gibraltar", region: "Europe" },
  { _id: "GR", name: "Greece", region: "Europe" },
  { _id: "GG", name: "Guernsey", region: "Europe" },
  { _id: "HU", name: "Hungary", region: "Europe" },
  { _id: "IS", name: "Iceland", region: "Europe" },
  { _id: "IE", name: "Ireland", region: "Europe" },
  { _id: "IM", name: "Isle of Man", region: "Europe" },
  { _id: "IT", name: "Italy", region: "Europe" },
  { _id: "JE", name: "Jersey", region: "Europe" },
  { _id: "XK", name: "Kosovo", region: "Europe" },
  { _id: "LV", name: "Latvia", region: "Europe" },
  { _id: "LI", name: "Liechtenstein", region: "Europe" },
  { _id: "LT", name: "Lithuania", region: "Europe" },
  { _id: "LU", name: "Luxembourg", region: "Europe" },
  { _id: "MT", name: "Malta", region: "Europe" },
  { _id: "MD", name: "Moldova", region: "Europe" },
  { _id: "MC", name: "Monaco", region: "Europe" },
  { _id: "ME", name: "Montenegro", region: "Europe" },
  { _id: "NL", name: "Netherlands", region: "Europe" },
  { _id: "MK", name: "North Macedonia", region: "Europe" },
  { _id: "NO", name: "Norway", region: "Europe" },
  { _id: "PL", name: "Poland", region: "Europe" },
  { _id: "PT", name: "Portugal", region: "Europe" },
  { _id: "RO", name: "Romania", region: "Europe" },
  { _id: "RU", name: "Russia", region: "Europe" },
  { _id: "SM", name: "San Marino", region: "Europe" },
  { _id: "RS", name: "Serbia", region: "Europe" },
  { _id: "SK", name: "Slovakia", region: "Europe" },
  { _id: "SI", name: "Slovenia", region: "Europe" },
  { _id: "ES", name: "Spain", region: "Europe" },
  { _id: "SJ", name: "Svalbard and Jan Mayen", region: "Europe" },
  { _id: "SE", name: "Sweden", region: "Europe" },
  { _id: "CH", name: "Switzerland", region: "Europe" },
  { _id: "UA", name: "Ukraine", region: "Europe" },
  { _id: "GB", name: "United Kingdom", region: "Europe" },
  { _id: "VA", name: "Vatican City", region: "Europe" },
  // ],
  // Oceania: [
  { _id: "AS", name: "American Samoa", region: "Oceania" },
  { _id: "AU", name: "Australia", region: "Oceania" },
  { _id: "CX", name: "Christmas Island", region: "Oceania" },
  { _id: "CC", name: "Cocos (Keeling) Islands", region: "Oceania" },
  { _id: "CK", name: "Cook Islands", region: "Oceania" },
  { _id: "FJ", name: "Fiji", region: "Oceania" },
  { _id: "PF", name: "French Polynesia", region: "Oceania" },
  { _id: "GU", name: "Guam", region: "Oceania" },
  { _id: "KI", name: "Kiribati", region: "Oceania" },
  { _id: "MH", name: "Marshall Islands", region: "Oceania" },
  { _id: "FM", name: "Micronesia", region: "Oceania" },
  { _id: "NR", name: "Nauru", region: "Oceania" },
  { _id: "NC", name: "New Caledonia", region: "Oceania" },
  { _id: "NZ", name: "New Zealand", region: "Oceania" },
  { _id: "NU", name: "Niue", region: "Oceania" },
  { _id: "NF", name: "Norfolk Island", region: "Oceania" },
  { _id: "MP", name: "Northern Mariana Islands", region: "Oceania" },
  { _id: "PW", name: "Palau", region: "Oceania" },
  { _id: "PG", name: "Papua New Guinea", region: "Oceania" },
  { _id: "PN", name: "Pitcairn Islands", region: "Oceania" },
  { _id: "WS", name: "Samoa", region: "Oceania" },
  { _id: "SB", name: "Solomon Islands", region: "Oceania" },
  { _id: "TK", name: "Tokelau", region: "Oceania" },
  { _id: "TO", name: "Tonga", region: "Oceania" },
  { _id: "TV", name: "Tuvalu", region: "Oceania" },
  { _id: "VU", name: "Vanuatu", region: "Oceania" },
  { _id: "WF", name: "Wallis and Futuna", region: "Oceania" },
  // ],
];
